version: '3.7'
services:
  postgres-server:    # The Postgres Database Service
    image: postgres:latest
    container_name: postgres-server
    restart: always
    volumes:
      - ./zbx_env/var/lib/postgresql/data:/var/lib/postgresql/data:rw
    env_file:
     - .env_pgsql
   
  zabbix-server:     # The main Zabbix Server Software Service
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: zabbix-server
    restart: always
    env_file:
     - .env_pgsql
     - .env_zbx
    ports:
      - 10051:10051 
    depends_on:
      - postgres-server
   
  zabbix-web:    # The main Zabbix web UI or interface
    image: zabbix/zabbix-web-nginx-pgsql:alpine-4.4.5
    container_name: zabbix-web
    restart: always
    ports:
      - 80:80
      - 8443:443
    env_file:
     - .env_web
    depends_on:
      - postgres-server
      - zabbix-server
 
  zabbix-agent:   # Zabbix agent service that tracks usage and send to zabbix server
    image: zabbix/zabbix-agent:latest
    container_name: zabbix-agent
    ports:
      - "10050:10050"
    privileged: true   #access mode for allowing resource access
    network_mode: "host"
    restart: unless-stopped
    env_file:
     - .env_agent